# **======================================**

# **Machine Learning Basics**

# **======================================**

### ***EDA BASIC WITH PANDAS, NUMPY, SEABORN, MATPLOTLIB DONE***
### ***NOW ITS TIME FOR SCIKIT LEARN LIBRARY***

# **======================================**

In [1]:
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.impute import SimpleImputer

In [2]:
dts = pd.read_csv('fifa_eda.csv')
dts.head()

ID               Name  Age Nationality  Overall  Potential  \
0  158023           L. Messi   31   Argentina       94         94   
1   20801  Cristiano Ronaldo   33    Portugal       94         94   
2  190871          Neymar Jr   26      Brazil       92         93   
3  193080             De Gea   27       Spain       91         93   
4  192985       K. De Bruyne   27     Belgium       91         92   

                  Club     Value   Wage Preferred Foot  \
0         FC Barcelona  110500.0  565.0           Left   
1             Juventus   77000.0  405.0          Right   
2  Paris Saint-Germain  118500.0  290.0          Right   
3    Manchester United   72000.0  260.0          Right   
4      Manchester City  102000.0  355.0          Right   

   International Reputation  Skill Moves Position  Joined  \
0                       5.0          4.0       RF    2004   
1                       5.0          5.0       ST    2018   
2                       5.0          5.0       LW    2017   
3                       4.0          1.0       GK    2011   
4                       4.0          4.0      RCM    2015   

  Contract Valid Until    Height  Weight  Release Clause  
0           2021-01-01  5.583333   159.0        226500.0  
1           2022-01-01  6.166667   183.0        127100.0  
2           2022-01-01  5.750000   150.0        228100.0  
3           2020-01-01  6.333333   168.0        138600.0  
4           2023-01-01  5.916667   154.0        196400.0

In [3]:
dts.info()
dts.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   ID                        18207 non-null  int64  
 1   Name                      18207 non-null  object 
 2   Age                       18207 non-null  int64  
 3   Nationality               18207 non-null  object 
 4   Overall                   18207 non-null  int64  
 5   Potential                 18207 non-null  int64  
 6   Club                      17966 non-null  object 
 7   Value                     17955 non-null  float64
 8   Wage                      18207 non-null  float64
 9   Preferred Foot            18207 non-null  object 
 10  International Reputation  18159 non-null  float64
 11  Skill Moves               18159 non-null  float64
 12  Position                  18207 non-null  object 
 13  Joined                    18207 non-null  int64  
 14  Contra

ID                            0
Name                          0
Age                           0
Nationality                   0
Overall                       0
Potential                     0
Club                        241
Value                       252
Wage                          0
Preferred Foot                0
International Reputation     48
Skill Moves                  48
Position                      0
Joined                        0
Contract Valid Until        289
Height                        0
Weight                        0
Release Clause                0
dtype: int64

In [4]:
floatC = dts.select_dtypes(include='float64').columns
#dtns = dts.select_dtypes(include='number' and 'float64')
#dtns.info()

In [5]:
intC = dts.select_dtypes(include='int64').columns

In [6]:
si = SimpleImputer(strategy="mean")
ar = si.fit_transform(dts[floatC])

In [7]:
#newdts = pd.DataFrame(ar,columns=dts.select_dtypes(include='float64').columns)
newdts = pd.DataFrame(ar,columns=floatC)

In [8]:
for col in intC:
    newdts[col] = dts[col]

In [9]:
non_intC = dts.select_dtypes(exclude=['int64','float64']).columns
for col in non_intC:
    newdts[col] = dts[col]

In [10]:
newdts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Value                     18207 non-null  float64
 1   Wage                      18207 non-null  float64
 2   International Reputation  18207 non-null  float64
 3   Skill Moves               18207 non-null  float64
 4   Height                    18207 non-null  float64
 5   Weight                    18207 non-null  float64
 6   Release Clause            18207 non-null  float64
 7   ID                        18207 non-null  int64  
 8   Age                       18207 non-null  int64  
 9   Overall                   18207 non-null  int64  
 10  Potential                 18207 non-null  int64  
 11  Joined                    18207 non-null  int64  
 12  Name                      18207 non-null  object 
 13  Nationality               18207 non-null  object 
 14  Club  

In [11]:
newdts.isnull().sum()

Value                         0
Wage                          0
International Reputation      0
Skill Moves                   0
Height                        0
Weight                        0
Release Clause                0
ID                            0
Age                           0
Overall                       0
Potential                     0
Joined                        0
Name                          0
Nationality                   0
Club                        241
Preferred Foot                0
Position                      0
Contract Valid Until        289
dtype: int64

In [12]:
newdts['Club']=newdts['Club'].bfill()
newdts['Contract Valid Until']=newdts['Contract Valid Until'].bfill()
newdts.isnull().sum()

Value                       0
Wage                        0
International Reputation    0
Skill Moves                 0
Height                      0
Weight                      0
Release Clause              0
ID                          0
Age                         0
Overall                     0
Potential                   0
Joined                      0
Name                        0
Nationality                 0
Club                        0
Preferred Foot              0
Position                    0
Contract Valid Until        0
dtype: int64

### **ONEHOTENCODING**

In [13]:
dnx = pd.read_csv("loan-test.csv")
dnx.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [14]:
dnx['Gender']=dnx['Gender'].bfill()
dnx['Dependents']=dnx['Dependents'].bfill()
dnx['Self_Employed']=dnx['Self_Employed'].ffill()
dnx['LoanAmount']=dnx['LoanAmount'].mean()
dnx['Loan_Amount_Term']=dnx['Loan_Amount_Term'].mean()
dnx['Credit_History']=dnx['Credit_History'].ffill()
dnx.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0  136.132597        342.537396   
1             3076               1500  136.132597        342.537396   
2             5000               1800  136.132597        342.537396   
3             2340               2546  136.132597        342.537396   
4             3276                  0  136.132597        342.537396   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             1.0         Urban  
4             1.0         Urban

In [15]:
dnx.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [16]:
en_data = dnx[['Gender','Married']]
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  367 non-null    bool 
 1   Gender_Male    367 non-null    bool 
 2   Married_No     367 non-null    bool 
 3   Married_Yes    367 non-null    bool 
dtypes: bool(4)
memory usage: 1.6 KB


In [17]:
en_data

Gender Married
0     Male     Yes
1     Male     Yes
2     Male     Yes
3     Male     Yes
4     Male      No
..     ...     ...
362   Male     Yes
363   Male     Yes
364   Male      No
365   Male     Yes
366   Male      No

[367 rows x 2 columns]

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
ohe = OneHotEncoder()
ohe.fit_transform(en_data)

<367x4 sparse matrix of type '<class 'numpy.float64'>'
	with 734 stored elements in Compressed Sparse Row format>

In [20]:
arx = ohe.fit_transform(en_data).toarray()

In [21]:
pd.DataFrame(arx,columns=["Gender_Female","Gender_Male","Married_No","Married_Yes"])

Gender_Female  Gender_Male  Married_No  Married_Yes
0              0.0          1.0         0.0          1.0
1              0.0          1.0         0.0          1.0
2              0.0          1.0         0.0          1.0
3              0.0          1.0         0.0          1.0
4              0.0          1.0         1.0          0.0
..             ...          ...         ...          ...
362            0.0          1.0         0.0          1.0
363            0.0          1.0         0.0          1.0
364            0.0          1.0         1.0          0.0
365            0.0          1.0         0.0          1.0
366            0.0          1.0         1.0          0.0

[367 rows x 4 columns]

### **LABELENCODING**

In [22]:
df = pd.DataFrame({"name":["asus","cat","dog","black","cow"]})
df

name
0   asus
1    cat
2    dog
3  black
4    cow

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le = LabelEncoder()
le.fit_transform(df["name"])

array([0, 2, 4, 1, 3])

In [25]:
df['en_name'] = le.fit_transform(df["name"])
df

name  en_name
0   asus        0
1    cat        2
2    dog        4
3  black        1
4    cow        3

In [26]:
dataset = pd.read_csv("loan-test.csv")
dataset.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [27]:
la = LabelEncoder()
la.fit(dataset['Property_Area'])

LabelEncoder()

In [28]:
la.transform(dataset['Property_Area'])

array([2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2,
       2, 2, 2, 0, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 1,
       2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 0, 1, 1, 1, 1, 2, 1, 0, 2, 1,
       1, 1, 1, 0, 1, 1, 2, 0, 1, 2, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 2, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 2, 1, 2, 1, 0, 1, 2, 0, 1, 1, 2, 0, 1, 2,
       1, 1, 2, 1, 0, 1, 1, 0, 2, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 1, 2, 0,
       0, 2, 2, 2, 0, 0, 1, 1, 0, 0, 2, 1, 0, 2, 1, 0, 1, 2, 2, 2, 0, 2,
       0, 1, 2, 0, 1, 0, 0, 1, 2, 0, 0, 1, 2, 2, 1, 0, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 2, 1, 1, 2, 0, 2, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 2, 1, 0,
       2, 0, 0, 2, 2, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 0, 2, 1, 0, 0, 2,
       2, 0, 2, 0, 1, 2, 2, 0, 0, 2, 1, 2, 0, 1, 2, 2, 1, 0, 1, 2, 2, 1,
       1, 0, 1, 1, 2, 2, 1, 0, 2, 1, 1, 2, 2, 0, 0, 2, 0, 0, 1, 1, 0, 0,
       0, 1, 2, 0, 0, 0, 2, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 2, 0, 2, 2,
       0, 0, 2, 2, 1, 2, 0, 2, 2, 1, 1, 0, 1, 0, 2,

In [29]:
dataset['Property_Area'].unique()

array(['Urban', 'Semiurban', 'Rural'], dtype=object)

### **RODINAL ENCODING**

In [30]:
df = pd.DataFrame({"size":['s','m','l','xl','s','m','l','s','s','l','xl','m']})
ordata = [['s','m','l','xl']]

In [31]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=ordata)
oe.fit(df[['size']])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [32]:
oe.transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [3.],
       [1.]])

In [33]:
df['size_en'] = oe.transform(df[['size']])
df

size  size_en
0     s      0.0
1     m      1.0
2     l      2.0
3    xl      3.0
4     s      0.0
5     m      1.0
6     l      2.0
7     s      0.0
8     s      0.0
9     l      2.0
10   xl      3.0
11    m      1.0